import ffmpegNoticesJson from "./generated/ffmpegNotices.json";

/** A license or attribution notice for the open-source licenses page. */
export interface LicenseNotice {
  title: string;
  text: string;
}

/**
 * Notices for the bundled ffmpeg builds: one per platform, then the GNU license texts,
 * then one per statically linked library. Generated by `mise run ffmpeg-notices`.
 */
export const ffmpegNotices: readonly LicenseNotice[] = ffmpegNoticesJson;
