import { expandDependencyNotices } from "./dependencyNotices.ts";
import ffmpegNoticesJson from "./generated/ffmpegNotices.json";
import type { LicenseNotice, LicenseNoticeGroup } from "./licenseNotice.ts";

export type {
  DependencyNoticeData,
  PackageNoticeData,
} from "./dependencyNotices.ts";
export { expandDependencyNotices } from "./dependencyNotices.ts";
export type { LicenseNotice, LicenseNoticeGroup } from "./licenseNotice.ts";

/**
 * Notices for the bundled ffmpeg builds: one per platform, then the GNU license texts,
 * then one per statically linked library. Generated by `mise run ffmpeg-notices`.
 */
export const ffmpegNotices: readonly LicenseNotice[] = ffmpegNoticesJson;

/**
 * Loads every notice for the open-source licenses page: the ffmpeg builds, then the Rust crates and the npm packages that ship.
 * The dependency notices are loaded on demand, because they are large and only the licenses page needs them.
 * Generated by `mise run license-notices`.
 */
export async function loadLicenseNoticeGroups(): Promise<LicenseNoticeGroup[]> {
  const { default: dependencyNotices } = await import(
    "./generated/dependencyNotices.json"
  );
  return [
    { title: "FFmpeg", notices: ffmpegNotices },
    ...expandDependencyNotices(dependencyNotices),
  ];
}
