import crateNoticesJson from "./generated/crateNotices.json";
import ffmpegNoticesJson from "./generated/ffmpegNotices.json";

/** A license or attribution notice for the open-source licenses page. */
export interface LicenseNotice {
  title: string;
  text: string;
}

/**
 * Notices for the bundled ffmpeg builds: one per platform, then the GNU license texts,
 * then one per statically linked library. Generated by `mise run ffmpeg-notices`.
 */
export const ffmpegNotices: readonly LicenseNotice[] = ffmpegNoticesJson;

/**
 * Notices for the Rust crates whose licenses ask for their text to ship with the app, one per crate.
 * Generated by `mise run crate-notices` from `scripts/crate-notices/crates.json`.
 */
export const crateNotices: readonly LicenseNotice[] = crateNoticesJson;

/** Every notice for the open-source licenses page: the ffmpeg notices, then the crate notices. */
export const licenseNotices: readonly LicenseNotice[] = [
  ...ffmpegNotices,
  ...crateNotices,
];
