//! Host-side bindings for the WIT package `easyimmerse:plugin`.
//!
//! The WIT files under `wit/` are the source of truth. This crate generates
//! Rust bindings from them for the worlds the host loads. Guest bindings are
//! generated by each plugin's own toolchain from the same directory.

/// The directory holding the WIT package, for tools that read it at runtime.
pub const WIT_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/wit");

/// Bindings for the `plugin-base` world, which imports every host interface
/// and exports nothing. The `Host` traits for the five host interfaces live
/// here, and the worlds below reuse them.
pub mod base {
    wasmtime::component::bindgen!({
        path: "wit",
        world: "plugin-base",
        imports: { default: trappable },
    });
}

/// Bindings for the test-only `hello-plugin` world.
pub mod hello {
    wasmtime::component::bindgen!({
        path: "wit",
        world: "hello-plugin",
        imports: { default: trappable },
        with: {
            "easyimmerse:plugin/types": crate::base::easyimmerse::plugin::types,
            "easyimmerse:plugin/log": crate::base::easyimmerse::plugin::log,
            "easyimmerse:plugin/http": crate::base::easyimmerse::plugin::http,
            "easyimmerse:plugin/fs": crate::base::easyimmerse::plugin::fs,
            "easyimmerse:plugin/run-command": crate::base::easyimmerse::plugin::run_command,
            "easyimmerse:plugin/secrets": crate::base::easyimmerse::plugin::secrets,
        },
    });
}

/// Bindings for the test-only `media-source-fixture` world, which exports
/// `media-source` and `sandbox-probe`.
pub mod media_source_fixture {
    wasmtime::component::bindgen!({
        path: "wit",
        world: "media-source-fixture",
        imports: { default: trappable },
        with: {
            "easyimmerse:plugin/types": crate::base::easyimmerse::plugin::types,
            "easyimmerse:plugin/log": crate::base::easyimmerse::plugin::log,
            "easyimmerse:plugin/http": crate::base::easyimmerse::plugin::http,
            "easyimmerse:plugin/fs": crate::base::easyimmerse::plugin::fs,
            "easyimmerse:plugin/run-command": crate::base::easyimmerse::plugin::run_command,
            "easyimmerse:plugin/secrets": crate::base::easyimmerse::plugin::secrets,
        },
    });
}
