//! Tests against forms that Wikidata lists for German lexemes.

use std::collections::BTreeSet;

use super::deinflect;

/// Rows of inflected form, dictionary form and word class, generated by `fixtures/generate-wikidata-cases.cjs`.
const WIKIDATA_CASES: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/deinflection/german/fixtures/wikidata-cases.json"
));

/// Lexemes with forms that Wikidata lists but the deinflector does not trace back, by reason.
const EXPECTED_FAILURES: [&[&str]; 5] = [
    // Errors in Wikidata: misspelled forms (Commitmentents, Zauberspüche, weitergegeschert, kucktenm, Schad).
    &[
        "Commitment",
        "Klimawissenschaftlerin",
        "Zauberspruch",
        "weiterscheren",
        "kucken",
        "Schaden",
    ],
    // Forms listed under another spelling of the lemma (aufwendig, Schogunat).
    &["aufwändig", "Shogunat"],
    // Loanword plurals that grammis, unit 4065, does not describe.
    &[
        "Tuber",
        "Reflexiv",
        "Kosmetik",
        "Signor",
        "Bol",
        "Sephardi",
        "Aschkenasi",
        "Fellatio",
        "Schofar",
        "Dekompositum",
        "Spezialkorpus",
        "Pyrethrum",
        "Spielmannsepos",
        "Hexastylos",
        "Fibrinolytikum",
        "Luftwaffenbasis",
        "Adjektivabstraktum",
        "Praktikum",
        "Fakultas",
        "Seeklima",
        "Kontinentalklima",
        "Mastodon",
        "Atlas",
        "Kzin",
    ],
    // The plural Bauten of Bau and its compounds, which no source describes.
    &[
        "Backsteinbau",
        "Wagonbau",
        "Mehrzweckbau",
        "Zentralbau",
        "Waldumbau",
        "Knochenabbau",
        "Vorbau",
        "Trockenbau",
        "Oberbau",
        "Grundbau",
        "Kopfbau",
        "Schulneubau",
        "Verbindungsbau",
        "Repräsentationsbau",
        "Circusbau",
        "Prachtbau",
        "Komplettumbau",
        "Straßenausbau",
        "Ergänzungsbau",
        "Gemeindebau",
        "Flughafenausbau",
        "Industriebau",
        "Plattenbau",
        "Fertigbau",
        "Stahlbau",
        "Verwaltungsbau",
        "Profanbau",
        "Hotelbau",
        "Zirkusbau",
        "Sandsteinbau",
        "Radikalumbau",
        "Saalbau",
        "Erweiterungsbau",
        "Triumphbau",
        "Kasernenbau",
    ],
    // A consonant doubled before the comparative ending (hip, hipper), which no source describes.
    &["hip"],
];

#[test]
fn recovers_the_dictionary_form_of_every_wikidata_case_except_the_expected_failures() {
    let expected: BTreeSet<&str> = EXPECTED_FAILURES
        .iter()
        .flat_map(|group| group.iter().copied())
        .collect();
    assert_eq!(failing_lemmas(&cases()), expected);
}

#[test]
fn recovers_at_least_97_percent_of_the_wikidata_cases() {
    let cases = cases();
    let failures = cases.iter().filter(|case| !recovers(case)).count();
    assert!(failures * 100 <= cases.len() * 3);
}

fn cases() -> Vec<(String, String, String)> {
    serde_json::from_str(WIKIDATA_CASES).expect("the fixture is valid JSON")
}

fn failing_lemmas(cases: &[(String, String, String)]) -> BTreeSet<&str> {
    cases
        .iter()
        .filter(|case| !recovers(case))
        .map(|(_, term, _)| term.as_str())
        .collect()
}

/// Whether deinflecting the form yields the dictionary form, in its word class or as another spelling of the form.
fn recovers((inflected, term, word_class): &(String, String, String)) -> bool {
    deinflect(inflected).iter().any(|candidate| {
        &candidate.term == term
            && (candidate.inflections.is_empty()
                || candidate
                    .word_classes
                    .iter()
                    .any(|class| class == word_class))
    })
}
