/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/conversion-cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConversionCache"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversion-cache/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Removes every cached conversion that is not in use right now. */
        post: operations["clearConversionCache"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversions/{key}/index.m3u8": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConversionPlaylist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversions/{key}/init.mp4": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConversionInitSegment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversions/{key}/{segment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConversionSegment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDictionaries"];
        put?: never;
        post: operations["importDictionary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionaries/import-local": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importLocalDictionary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionaries/{id}/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lookupTerm"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parses a document sent as the raw request body.
         * @description The format is taken from the `format` query parameter, then from the `Content-Type`
         *     header, and otherwise detected from the bytes.
         */
        post: operations["parseDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/parse-local": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["parseLocalDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reports that the server is up. The only route that needs no token. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serves the OpenAPI document. The router attaches the document as a request extension
         *     once it has been assembled.
         */
        get: operations["getOpenApiDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPreference"];
        put: operations["setPreference"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMediaFiles"];
        put?: never;
        /**
         * Adds a media file to a project. A `path` source must name an existing file on the
         *     server's machine, which only a token allowed to read local paths may do.
         */
        post: operations["addMediaFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeMediaFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/media/{media_id}/playback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plans playback for the client's environment. A converting plan registers the conversion
         *     and names its playlist. Without a conversion service, anything that would need conversion
         *     comes back unsupported with the reason `conversion_unavailable`.
         */
        post: operations["planMediaPlayback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/media/{media_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Streams the file's bytes. Honors `Range` with 206 and 416 responses and advertises
         *     `Accept-Ranges: bytes`. The content type is guessed from the file extension.
         */
        get: operations["streamMediaFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/media/{media_id}/subtitle-tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMediaSubtitleTracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/media/{media_id}/track-selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setMediaTrackSelection"];
        post?: never;
        delete: operations["clearMediaTrackSelection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/media/{media_id}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMediaTracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/media/{media_id}/waveform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns 100 peaks per second of the window, from the audio track the user chose for the
         *     file, else its default audio track. A file without audio yields no peaks.
         */
        get: operations["getMediaWaveform"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timed-text/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["parseTimedText"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddMediaFileRequest: {
            /** @description The name shown in the project's media list, usually the file name. */
            name: string;
            source: components["schemas"]["MediaFileSource"];
        };
        /** @description The body of every error response. */
        ApiError: {
            /** @description A stable, machine-readable identifier such as `unauthorized`. */
            code: string;
            message: string;
        };
        AudioAction: {
            /** @enum {string} */
            action: "copy";
            /** Format: int32 */
            index: number;
        } | {
            /** @enum {string} */
            action: "transcode";
            /** Format: int32 */
            index: number;
            target: components["schemas"]["AudioTarget"];
        };
        /** @enum {string} */
        AudioTarget: "aac" | "flac";
        /**
         * @description A media element's `canPlayType` answer. The empty string becomes `No`.
         * @enum {string}
         */
        CanPlayAnswer: "probably" | "maybe" | "no";
        Chapter: {
            paragraphs: string[];
            title?: string | null;
        };
        /** @enum {string} */
        ContainerFormat: "mp4" | "matroska" | "mp3" | "ogg" | "wav" | "flac" | "adts" | "mpeg_ts" | "avi";
        ContainerInfo: {
            /**
             * Format: int64
             * @description The overall bit rate of the file in bits per second.
             */
            bit_rate?: number | null;
            /** Format: int64 */
            duration_ms?: number | null;
            format: components["schemas"]["ContainerFormat"];
            /** Format: int64 */
            start_ms?: number | null;
            tracks: components["schemas"]["TrackInfo"][];
        };
        /** @description Sizes are in bytes. */
        ConversionCacheStatus: {
            /**
             * Format: int64
             * @description The size the cache may grow to when disk space allows.
             */
            budget_bytes: number;
            /** Format: int64 */
            free_bytes: number;
            /**
             * Format: int64
             * @description The size the cache may currently grow to: the budget, reduced when free space is short.
             */
            limit_bytes: number;
            /** @description True when free disk space, not the budget, limits the cache. */
            space_low: boolean;
            /** Format: int64 */
            usage_bytes: number;
        };
        ConversionPlan: {
            audio?: components["schemas"]["AudioAction"] | null;
            reasons: components["schemas"]["ConversionReason"][];
            video?: components["schemas"]["VideoAction"] | null;
        };
        /**
         * @description Why the file is converted rather than played directly.
         * @enum {string}
         */
        ConversionReason: "container_unsupported" | "inaccurate_seeking" | "non_default_tracks" | "codec_unsupported";
        /**
         * @description One text segment with the time range during which it is shown.
         *
         *     The text keeps any inline markup from the source file, such as `<i>`, and joins
         *     multiple lines with `\n`.
         */
        Cue: {
            /** Format: int64 */
            end_ms: number;
            /** Format: int32 */
            index: number;
            /** Format: int64 */
            start_ms: number;
            text: string;
        };
        DictionarySummary: {
            /** Format: int64 */
            entry_count: number;
            id: string;
            title: string;
        };
        Document: {
            chapters: components["schemas"]["Chapter"][];
            language?: string | null;
            title: string;
        };
        /** @enum {string} */
        DocumentFormat: "epub" | "plain_text";
        HealthResponse: {
            status: string;
        };
        ImportLocalDictionaryRequest: {
            path: string;
        };
        ListDictionariesResponse: {
            dictionaries: components["schemas"]["DictionarySummary"][];
        };
        ListMediaFilesResponse: {
            media_files: components["schemas"]["MediaFile"][];
        };
        ListProjectsResponse: {
            projects: components["schemas"]["ProjectSummary"][];
        };
        LookupResponse: {
            entries: components["schemas"]["TermEntry"][];
        };
        /** @description A video or audio file added to a project. */
        MediaFile: {
            /**
             * Format: int64
             * @description Milliseconds since the Unix epoch.
             */
            created_at_ms: number;
            id: components["schemas"]["MediaFileId"];
            /** @description The name shown in the project's media list, usually the file name. */
            name: string;
            project_id: components["schemas"]["ProjectId"];
            source: components["schemas"]["MediaFileSource"];
            /**
             * @description The user's saved choice of video and audio tracks, as the JSON the media crate
             *     defines. Null until the user has chosen.
             */
            track_selection_json?: string | null;
        };
        MediaFileId: string;
        /**
         * @description Where the bytes of a media file come from.
         *
         *     The `path` variant names a file on the machine running the server. The `browser_file`
         *     variant describes a file the web app holds in memory; the server never sees its bytes,
         *     so it records only what identifies the file when the user picks it again.
         */
        MediaFileSource: {
            /** @enum {string} */
            kind: "path";
            path: string;
        } | {
            /** @enum {string} */
            kind: "browser_file";
            /**
             * Format: int64
             * @description The file's modification time in milliseconds since the Unix epoch.
             */
            last_modified_ms: number;
            /** Format: int64 */
            size: number;
        };
        ParseLocalDocumentRequest: {
            format?: components["schemas"]["DocumentFormat"] | null;
            path: string;
        };
        /** @description The request body shared by the HTTP route and the WebAssembly facade. */
        ParseTimedTextRequest: {
            format?: components["schemas"]["TimedTextFormat"] | null;
            source: components["schemas"]["TextSource"];
        };
        PictureSize: {
            /** Format: int32 */
            height: number;
            /** Format: int32 */
            width: number;
        };
        /**
         * @description The browser engine behind the media element, decided from the user agent.
         * @enum {string}
         */
        PlaybackEngine: "webkit" | "chromium" | "gecko";
        PlaybackEnvironment: {
            /** @description The answer to `canPlayType` for the file's direct MIME type with codecs. */
            can_play_type: components["schemas"]["CanPlayAnswer"];
            engine: components["schemas"]["PlaybackEngine"];
            /** @description The RFC 6381 codec strings that `MediaSource.isTypeSupported` accepts in fragmented MP4. */
            mse_codec_strings: string[];
        };
        PlaybackPlan: {
            /** @enum {string} */
            kind: "direct";
        } | (components["schemas"]["ConversionPlan"] & {
            /** @enum {string} */
            kind: "convert";
        }) | {
            /** @enum {string} */
            kind: "unsupported";
            reason: components["schemas"]["UnsupportedReason"];
        };
        PlaybackRequest: {
            environment: components["schemas"]["PlaybackEnvironment"];
            preferred_audio_target?: components["schemas"]["AudioTarget"] | null;
            selection?: components["schemas"]["TrackSelection"] | null;
        };
        PlaybackResponse: {
            plan: components["schemas"]["PlaybackPlan"];
            /** @description The path of the HLS playlist, present only when the plan converts. */
            playlist_path?: string | null;
        };
        /** @description A preference value. `null` means the preference has not been set. */
        PreferenceValue: {
            value?: string | null;
        };
        ProjectId: string;
        ProjectSummary: {
            /** @description An RFC 3339 timestamp. */
            created_at: string;
            id: components["schemas"]["ProjectId"];
            language: string;
            name: string;
        };
        /** @description A positive ratio of two integers, such as a timebase of `1/90000` or a frame rate of `30000/1001`. */
        Rational: {
            /** Format: int64 */
            den: number;
            /** Format: int64 */
            num: number;
        };
        SubtitleTracksResponse: {
            tracks: components["schemas"]["TrackInfo"][];
        };
        TermEntry: {
            definitions: string[];
            reading?: string | null;
            tags: string[];
            term: string;
        };
        /**
         * @description Where the text of a request comes from.
         *
         *     The `path` variant names a file on the machine running the server. The server resolves
         *     it, and only for requests authenticated with the per-launch token. The WebAssembly build
         *     supports only the `inline` variant.
         */
        TextSource: {
            /** @enum {string} */
            kind: "inline";
            text: string;
        } | {
            /** @enum {string} */
            kind: "path";
            path: string;
        };
        /** @enum {string} */
        TimedTextFormat: "srt" | "vtt";
        TimedTextTrack: {
            cues: components["schemas"]["Cue"][];
            format: components["schemas"]["TimedTextFormat"];
        };
        /** @description One stream inside a container. Fields the source does not state are `None`. */
        TrackInfo: {
            /** Format: int64 */
            bit_rate?: number | null;
            /** Format: int32 */
            channels?: number | null;
            /** @description ffmpeg's name for the codec, such as `h264`, `aac`, or `subrip`. */
            codec: string;
            /**
             * @description The RFC 6381 codec string in the spelling Media Source Extensions accept,
             *     or `None` when the codec cannot be carried in fragmented MP4.
             */
            codec_string?: string | null;
            /**
             * Format: int32
             * @description The identifier the container itself uses for the track, such as the MP4 track id
             *     or the Matroska track number, when known.
             */
            container_track_id?: number | null;
            frame_rate?: components["schemas"]["Rational"] | null;
            /** Format: int32 */
            height?: number | null;
            /**
             * Format: int32
             * @description The stream's position counted over all stream kinds, as in ffmpeg's `0:N`.
             */
            index: number;
            interlaced: boolean;
            is_default: boolean;
            kind: components["schemas"]["TrackKind"];
            /** @description The language tag stored in the container, or `None` when it is undetermined. */
            language?: string | null;
            /** Format: int64 */
            level?: number | null;
            /** @description ffmpeg's name for the codec profile, such as `High` or `LC`. */
            profile?: string | null;
            /** Format: int32 */
            sample_rate?: number | null;
            /** Format: int64 */
            start_ms?: number | null;
            title?: string | null;
            /** Format: int32 */
            width?: number | null;
        };
        /** @enum {string} */
        TrackKind: "video" | "audio" | "subtitle" | "other";
        TrackSelection: {
            /** Format: int32 */
            audio?: number | null;
            /** Format: int32 */
            video?: number | null;
        };
        TracksResponse: {
            container: components["schemas"]["ContainerInfo"];
            default_selection: components["schemas"]["TrackSelection"];
            /**
             * @description The MIME type with codecs to pass to `canPlayType`, or `None` when the file's own bytes
             *     cannot play in a media element at all.
             */
            direct_mime_type?: string | null;
        };
        /** @enum {string} */
        UnsupportedReason: "no_tracks" | "track_not_found" | "video_codec_unsupported" | "audio_codec_unsupported" | "conversion_unavailable" | "picture_too_tall";
        VideoAction: {
            /** @enum {string} */
            action: "copy";
            /** Format: int32 */
            index: number;
        } | {
            /** @enum {string} */
            action: "transcode";
            /** Format: int64 */
            bit_rate: number;
            deinterlace: boolean;
            encoder: string;
            /** Format: int32 */
            index: number;
            scale_to?: components["schemas"]["PictureSize"] | null;
        };
        /**
         * @description One window of waveform peaks: 100 per second from `start_ms`, each the loudest sample of the
         *     loudest channel in its hundredth of a second, from 0 (silence) to 255 (full scale).
         */
        WaveformResponse: {
            peaks: number[];
            /** Format: int64 */
            start_ms: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getConversionCache: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The cache's usage and limits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversionCacheStatus"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description This server does not convert media (code `conversion_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    clearConversionCache: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The cache's usage and limits after clearing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversionCacheStatus"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description This server does not convert media (code `conversion_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getConversionPlaylist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The conversion's cache key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The on-demand HLS playlist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.apple.mpegurl": string;
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No conversion has this key */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description This server does not convert media (code `conversion_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getConversionInitSegment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The conversion's cache key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The fragmented MP4 init segment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "video/mp4": number[];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No conversion has this key */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description ffmpeg failed (code `conversion_failed`) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description This server does not convert media (code `conversion_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The segment was not produced in time (code `segment_timeout`) */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getConversionSegment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The conversion's cache key */
                key: string;
                /** @description A segment file name from the playlist, such as `s00042.m4s` */
                segment: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The fragmented MP4 media segment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "video/mp4": number[];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No conversion has this key, or the playlist has no such segment */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description ffmpeg failed (code `conversion_failed`) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description This server does not convert media (code `conversion_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The segment was not produced in time (code `segment_timeout`) */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listDictionaries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every imported dictionary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDictionariesResponse"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    importDictionary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The dictionary archive */
        requestBody?: {
            content: {
                "application/zip": unknown;
            };
        };
        responses: {
            /** @description The dictionary was imported */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionarySummary"];
                };
            };
            /** @description The archive could not be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    importLocalDictionary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportLocalDictionaryRequest"];
            };
        };
        responses: {
            /** @description The dictionary was imported */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionarySummary"];
                };
            };
            /** @description The archive could not be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The token may not read local paths */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No file at the given path */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    lookupTerm: {
        parameters: {
            query: {
                /** @description The exact term or reading to find. */
                term: string;
            };
            header?: never;
            path: {
                /** @description The dictionary id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The entries matching the term exactly */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookupResponse"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No dictionary has the id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    parseDocument: {
        parameters: {
            query?: {
                /** @description Overrides format detection. */
                format?: components["schemas"]["DocumentFormat"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The document file */
        requestBody?: {
            content: {
                "application/epub+zip": unknown;
                "text/plain": unknown;
            };
        };
        responses: {
            /** @description The parsed document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description The document could not be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    parseLocalDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseLocalDocumentRequest"];
            };
        };
        responses: {
            /** @description The parsed document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description The document could not be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The token may not read local paths */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No file at the given path */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getOpenApiDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getPreference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The preference key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stored value, or null when unset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferenceValue"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    setPreference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The preference key */
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferenceValue"];
            };
        };
        responses: {
            /** @description The value was stored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The value was null */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every project, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListProjectsResponse"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listMediaFiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The project's media files, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMediaFilesResponse"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    addMediaFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMediaFileRequest"];
            };
        };
        responses: {
            /** @description The added media file */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaFile"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The token may not name local paths */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such project, or no file at the given path */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    removeMediaFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project id */
                id: string;
                /** @description The media file id */
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The media file was removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such media file in the project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    planMediaPlayback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project id */
                id: string;
                /** @description The media file id */
                media_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaybackRequest"];
            };
        };
        responses: {
            /** @description The plan and, when converting, the playlist path */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybackResponse"];
                };
            };
            /** @description The file could not be probed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The token may not read local paths */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such media file, no file at its path, or a browser-held file (code `not_resolvable`) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description This server cannot probe media (code `conversion_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    streamMediaFile: {
        parameters: {
            query?: {
                /** @description The bearer token, for media elements, which cannot send headers. */
                token?: string;
            };
            header?: never;
            path: {
                /** @description The project id */
                id: string;
                /** @description The media file id */
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The whole file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": number[];
                };
            };
            /** @description The requested byte range */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": number[];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The token may not read local paths */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such media file, no file at its path, or a source the server cannot read (code `not_resolvable`) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The range lies outside the file */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getMediaSubtitleTracks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project id */
                id: string;
                /** @description The media file id */
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The subtitle tracks embedded in the file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubtitleTracksResponse"];
                };
            };
            /** @description The file could not be probed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The token may not read local paths */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such media file, no file at its path, or a browser-held file (code `not_resolvable`) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description This server cannot probe media (code `conversion_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    setMediaTrackSelection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project id */
                id: string;
                /** @description The media file id */
                media_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackSelection"];
            };
        };
        responses: {
            /** @description The choice was saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such media file in the project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    clearMediaTrackSelection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project id */
                id: string;
                /** @description The media file id */
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The choice was cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such media file in the project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getMediaTracks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project id */
                id: string;
                /** @description The media file id */
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The probed container, the default track selection, and the MIME type for `canPlayType` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracksResponse"];
                };
            };
            /** @description The file could not be probed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The token may not read local paths */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such media file, no file at its path, or a browser-held file (code `not_resolvable`) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description This server cannot probe media (code `conversion_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getMediaWaveform: {
        parameters: {
            query: {
                /** @description The window start in player time, in milliseconds. */
                start_ms: number;
                /** @description The window end in player time, in milliseconds; at most five minutes after the start. */
                end_ms: number;
            };
            header?: never;
            path: {
                /** @description The project id */
                id: string;
                /** @description The media file id */
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The window's peaks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaveformResponse"];
                };
            };
            /** @description The window is inverted or longer than five minutes, or the file could not be probed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The token may not read local paths */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such media file, no file at its path, or a browser-held file (code `not_resolvable`) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Decoding failed (code `waveform_failed`) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description This server has no ffmpeg or no cache directory (code `waveform_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    parseTimedText: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseTimedTextRequest"];
            };
        };
        responses: {
            /** @description The parsed cues */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimedTextTrack"];
                };
            };
            /** @description The text could not be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The token may not read local paths */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No file at the given path */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected Host header */
            421: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
