use std::path::Path;

use tauri_build::{AppManifest, Attributes};

/// The built plugin that the `plugin-check` feature embeds.
const EMBEDDED_PLUGIN_DIR: &str = "../../../plugins/hello-rust/dist";

/// The app's own Tauri commands, which get `allow-` and `deny-` permissions generated
/// under `permissions/autogenerated/` for the capability files to reference.
const COMMANDS: &[&str] = &["check_plugin_host"];

fn main() {
    if std::env::var_os("CARGO_FEATURE_PLUGIN_CHECK").is_some() {
        require_embedded_plugin();
    }
    let manifest = AppManifest::new().commands(COMMANDS);
    tauri_build::try_build(Attributes::new().app_manifest(manifest))
        .expect("the Tauri build script failed");
}

/// Fails the build with a message naming the task that builds the plugin when it is missing.
fn require_embedded_plugin() {
    for file_name in ["plugin.wasm", "plugin.toml"] {
        let path = Path::new(EMBEDDED_PLUGIN_DIR).join(file_name);
        println!("cargo:rerun-if-changed={}", path.display());
        assert!(
            path.is_file(),
            "{} is missing; run `mise run plugins:build-rust` first",
            path.display()
        );
    }
}
