use std::error::Error;
use std::path::Path;

use tauri_build::{AppManifest, Attributes};

/// The built plugin that the `plugin-check` feature embeds.
const EMBEDDED_PLUGIN_DIR: &str = "../../../plugins/hello-rust/dist";

/// The app's own Tauri commands.
/// Each gets `allow-` and `deny-` permissions generated under `permissions/autogenerated/` for the capability files to reference.
const COMMANDS: &[&str] = &["check_plugin_host"];

/// The capability files that every build reads.
const CAPABILITIES: &str = "./capabilities/*.json";
/// The capability files that builds with the `webdriver` feature read.
/// Subdirectories hold the capabilities that name the WebDriver plugins' permissions,
/// which only exist when that feature compiles the plugins in.
const WEBDRIVER_CAPABILITIES: &str = "./capabilities/**/*.json";

fn main() -> Result<(), Box<dyn Error + Send + Sync>> {
    if std::env::var_os("CARGO_FEATURE_PLUGIN_CHECK").is_some() {
        require_embedded_plugin()?;
    }
    println!("cargo:rerun-if-changed=capabilities");
    let manifest = AppManifest::new().commands(COMMANDS);
    let attributes = Attributes::new()
        .app_manifest(manifest)
        .capabilities_path_pattern(capabilities_pattern());
    tauri_build::try_build(attributes)?;
    Ok(())
}

fn capabilities_pattern() -> &'static str {
    if std::env::var_os("CARGO_FEATURE_WEBDRIVER").is_some() {
        WEBDRIVER_CAPABILITIES
    } else {
        CAPABILITIES
    }
}

/// Fails the build with a message naming the task that builds the plugin when it is missing.
fn require_embedded_plugin() -> Result<(), String> {
    for file_name in ["plugin.wasm", "plugin.toml"] {
        let path = Path::new(EMBEDDED_PLUGIN_DIR).join(file_name);
        println!("cargo:rerun-if-changed={}", path.display());
        if !path.is_file() {
            return Err(format!(
                "{} is missing; run `mise run plugins:build-rust` first",
                path.display()
            ));
        }
    }
    Ok(())
}
