import { readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

/** Writes an `index.ts` barrel for the files ts-rs generated, since ts-rs writes none itself. */
const generatedDir = fileURLToPath(
  new URL("../src/generated", import.meta.url),
);

const moduleNames = readdirSync(generatedDir)
  .filter((file) => file.endsWith(".ts") && file !== "index.ts")
  .map((file) => file.slice(0, -".ts".length))
  .sort();

const lines = [
  "// Generated by scripts/writeGeneratedIndex.ts. Do not edit.",
  ...moduleNames.map((name) => `export type * from "./${name}";`),
  "",
];

writeFileSync(join(generatedDir, "index.ts"), lines.join("\n"));
console.log(`Wrote index.ts for ${moduleNames.length} generated modules.`);
