name: Install ffmpeg
description: Installs ffmpeg and ffprobe with the package manager of the operating system.

runs:
  using: composite
  steps:
    - name: Install ffmpeg on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt-get update && sudo apt-get install --yes ffmpeg

    - name: Install ffmpeg on macOS
      if: runner.os == 'macOS'
      shell: bash
      run: brew install ffmpeg

    - name: Install ffmpeg on Windows
      if: runner.os == 'Windows'
      shell: bash
      run: choco install ffmpeg --yes --no-progress

    - name: Show the ffmpeg version
      shell: bash
      run: ffmpeg -version
