//! A rule-based deinflector for Japanese verbs and i-adjectives.
//!
//! Each rule replaces an inflected kana ending with a base ending. Rules chain, so that
//! 食べさせられなかった is traced back through 食べさせられない, 食べさせられる and 食べさせる to 食べる.
//! The rule groups and the sources they are drawn from are listed in `docs/japanese-deinflection-sources.md`.

mod rule;
mod rules;
mod search;
mod word_class;

use super::Deinflection;

/// Lists the dictionary forms that the Japanese `text` may be an inflection of,
/// starting with the text itself, unchanged.
pub fn deinflect(text: &str) -> Vec<Deinflection> {
    search::search(text, rules::ALL)
}

#[cfg(test)]
pub(super) mod test_support {
    /// Whether deinflecting `text` yields `term` in `word_class` through exactly `inflections`.
    pub fn yields(text: &str, term: &str, word_class: &str, inflections: &[&str]) -> bool {
        super::deinflect(text).iter().any(|candidate| {
            candidate.term == term
                && candidate
                    .word_classes
                    .iter()
                    .any(|class| class == word_class)
                && candidate.inflections == inflections
        })
    }
}

#[cfg(test)]
mod tests {
    use super::deinflect;
    use super::test_support::yields;

    #[test]
    fn undoes_a_stack_of_inflections_outermost_first() {
        assert!(yields(
            "食べさせられなかった",
            "食べる",
            "v1",
            &["past", "negative", "passive", "causative"]
        ));
    }

    #[test]
    fn undoes_a_polite_stack_of_inflections() {
        assert!(yields(
            "読ませられていませんでした",
            "読む",
            "v5",
            &[
                "past",
                "negative",
                "polite",
                "progressive",
                "passive",
                "causative"
            ]
        ));
    }

    #[test]
    fn deinflects_a_noun_ending_in_ta_to_itself_alone() {
        assert_eq!(deinflect("かた").len(), 1);
    }

    #[test]
    fn deinflects_a_kanji_noun_to_itself_alone() {
        assert_eq!(deinflect("学生").len(), 1);
    }

    #[test]
    fn lists_each_term_and_inflection_chain_once() {
        let candidates = deinflect("食べられる");
        let unique = candidates.iter().filter(|candidate| {
            candidates
                .iter()
                .filter(|other| {
                    other.term == candidate.term && other.inflections == candidate.inflections
                })
                .count()
                == 1
        });
        assert_eq!(unique.count(), candidates.len());
    }

    #[test]
    fn merges_the_classes_of_candidates_with_the_same_chain() {
        let candidates = deinflect("帰れる");
        let potential = candidates
            .iter()
            .find(|candidate| candidate.term == "帰る" && candidate.inflections == ["potential"]);
        assert_eq!(
            potential.map(|candidate| candidate.word_classes.clone()),
            Some(vec!["v1".to_string(), "v5".to_string()])
        );
    }

    #[test]
    fn keeps_the_candidates_for_a_long_text_few() {
        assert!(deinflect("食べさせられていなかったらしいです").len() < 100);
    }

    /// Rows of inflected form, dictionary form and word class, generated by `fixtures/generate-kamiya-cases.cjs`.
    const KAMIYA_CASES: &str = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/deinflection/japanese/fixtures/kamiya-cases.json"
    ));

    #[test]
    fn recovers_the_dictionary_form_of_every_kamiya_codec_case() {
        let cases: Vec<(String, String, String)> =
            serde_json::from_str(KAMIYA_CASES).expect("the fixture is valid JSON");
        let failures: Vec<_> = cases
            .iter()
            .filter(|(inflected, term, word_class)| !recovers(inflected, term, word_class))
            .collect();
        assert_eq!(failures, Vec::<&(String, String, String)>::new());
    }

    fn recovers(inflected: &str, term: &str, word_class: &str) -> bool {
        deinflect(inflected).iter().any(|candidate| {
            candidate.term == term
                && candidate
                    .word_classes
                    .iter()
                    .any(|class| class == word_class)
        })
    }
}
