//! Checks the deinflector against forms generated by two independent sources, kamiya-codec and UniDic.
//! The fixtures and the scripts that generate them are in `fixtures/`.

use super::deinflect;

/// Rows of inflected form, dictionary form and word class, generated by `fixtures/generate-kamiya-cases.cjs`.
const KAMIYA_CASES: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/deinflection/japanese/fixtures/kamiya-cases.json"
));

/// Rows of inflected form, dictionary form, word class and UniDic conjugation type and form,
/// generated by `fixtures/generate-unidic-cases.cjs`.
const UNIDIC_CASES: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/deinflection/japanese/fixtures/unidic-cases.json"
));

#[test]
fn recovers_the_dictionary_form_of_every_kamiya_codec_case() {
    let cases: Vec<(String, String, String)> =
        serde_json::from_str(KAMIYA_CASES).expect("the fixture is valid JSON");
    let failures: Vec<_> = cases
        .iter()
        .filter(|(inflected, term, word_class)| !recovers(inflected, term, word_class))
        .collect();
    assert_eq!(failures, Vec::<&(String, String, String)>::new());
}

#[test]
fn recovers_the_dictionary_form_of_every_unidic_case() {
    let cases: Vec<(String, String, String, String)> =
        serde_json::from_str(UNIDIC_CASES).expect("the fixture is valid JSON");
    let failures: Vec<_> = cases
        .iter()
        .filter(|(inflected, term, word_class, _)| !recovers(inflected, term, word_class))
        .collect();
    assert_eq!(failures, Vec::<&(String, String, String, String)>::new());
}

fn recovers(inflected: &str, term: &str, word_class: &str) -> bool {
    deinflect(inflected).iter().any(|candidate| {
        candidate.term == term
            && candidate
                .word_classes
                .iter()
                .any(|class| class == word_class)
    })
}
